{
    'name': 'Specialist Journal',
    'version': '1.0.0',
    'author': 'Your Name',
    'category': 'Tools',
    'summary': 'Journal of specialist notes linked to partners',
    'description': 'Journal for specialists: templates + partner history.',
    'depends': ['base', 'mail'],
    'data': [
        'security/groups.xml',
        'security/ir.model.access.csv',
        'security/record_rules.xml',
        'views/wizard_report_views.xml',
        'views/template_views.xml',
        'views/journal_views.xml',
        'views/res_partner_inherit.xml',
        'reports/report_journal_action.xml',
        'reports/report_journal_template.xml',
        'reports/report_journal_action.xml',
        'reports/report_journal_template.xml',
    ],
    'installable': True,
    'application': False,
    'license': 'LGPL-3',
}
